[package]
name = "draw-dag"
version = "0.1.1"
edition = "2021"
description = "A draw DAGs to the terminal."
license = "Apache-2.0"

repository = "https://github.com/JonathanWoollett-Light/draw-dag"
readme = "./README.md"

[dependencies]